/**
 * @file Copies the Lucide icons used by the app into src/shared/icons.js.
 *
 * Every SVG primitive is converted to path data so the same definitions can be
 * rendered as inline SVG in the dashboard and as Path2D on the overlay canvas.
 * Run with `npm run icons:vendor` after changing ICON_NAMES.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const LUCIDE_DIR = path.join(ROOT, 'node_modules', 'lucide', 'dist', 'esm', 'icons');
const OUT_FILE = path.join(ROOT, 'src', 'shared', 'icons.js');

const ICON_NAMES = [
  // Navigation and actions
  'audio-lines', 'keyboard', 'wand-sparkles', 'app-window', 'chart-column', 'settings',
  'play', 'square-pen', 'trash', 'plus', 'x', 'check', 'rotate-ccw', 'upload', 'share-2', 'mic',
  'info', 'circle-check', 'circle-alert', 'triangle-alert', 'loader-circle',
  'volume-2', 'refresh-cw', 'lock', 'trophy',
  // Sound packs
  'phone', 'type', 'piano', 'keyboard-music', 'music-4', 'drum', 'zap', 'crosshair', 'swords',
  'coins', 'gamepad-2', 'droplets', 'activity', 'bird', 'hammer', 'dices', 'music', 'music-2',
  // Custom pack choices
  'audio-waveform', 'bell', 'star', 'heart', 'ghost', 'rocket', 'flame', 'guitar', 'cat', 'radio', 'disc-3',
  // Achievements
  'sparkles', 'crown', 'footprints', 'wind', 'rabbit', 'gauge', 'compass', 'headphones',
  'calendar-check', 'calendar-days', 'moon',
];

/**
 * @param {string | undefined} v - SVG attribute value.
 * @returns {number} The value as a number (0 when missing).
 */
const num = (v) => Number(v ?? 0);

/**
 * Converts one Lucide SVG node to path data.
 * @param {string} tag - SVG element name.
 * @param {Record<string, string>} a - Element attributes.
 * @returns {string} Path data equivalent to the element.
 */
function toPath(tag, a) {
  switch (tag) {
    case 'path':
      return a.d;
    case 'circle':
    case 'ellipse': {
      const rx = num(a.rx ?? a.r);
      const ry = num(a.ry ?? a.r);
      const cx = num(a.cx);
      const cy = num(a.cy);
      return `M${cx - rx} ${cy}a${rx} ${ry} 0 1 0 ${2 * rx} 0a${rx} ${ry} 0 1 0 ${-2 * rx} 0`;
    }
    case 'rect': {
      const x = num(a.x);
      const y = num(a.y);
      const w = num(a.width);
      const h = num(a.height);
      const r = Math.min(num(a.rx ?? a.ry), w / 2, h / 2);
      if (!r) return `M${x} ${y}h${w}v${h}h${-w}z`;
      return `M${x + r} ${y}h${w - 2 * r}a${r} ${r} 0 0 1 ${r} ${r}v${h - 2 * r}a${r} ${r} 0 0 1 ${-r} ${r}`
        + `h${-(w - 2 * r)}a${r} ${r} 0 0 1 ${-r} ${-r}v${-(h - 2 * r)}a${r} ${r} 0 0 1 ${r} ${-r}z`;
    }
    case 'line':
      return `M${a.x1} ${a.y1}L${a.x2} ${a.y2}`;
    case 'polyline':
    case 'polygon': {
      const pts = a.points.trim().split(/[\s,]+/);
      let d = `M${pts[0]} ${pts[1]}`;
      for (let i = 2; i < pts.length; i += 2) d += `L${pts[i]} ${pts[i + 1]}`;
      return tag === 'polygon' ? `${d}z` : d;
    }
    default:
      throw new Error(`Unsupported SVG element: ${tag}`);
  }
}

const icons = {};
for (const name of ICON_NAMES) {
  const file = path.join(LUCIDE_DIR, `${name}.mjs`);
  if (!fs.existsSync(file)) throw new Error(`Lucide has no icon named "${name}"`);
  const { default: node } = await import(pathToFileURL(file).href);
  icons[name] = node.map(([tag, attrs]) => toPath(tag, attrs));
}

const body = Object.entries(icons)
  .map(([name, paths]) => `  '${name}': [\n${paths.map((d) => `    '${d}',`).join('\n')}\n  ],`)
  .join('\n');

fs.writeFileSync(OUT_FILE, `/**
 * @file Icon path data (24x24 viewBox, 2px stroke), generated by scripts/vendor-icons.js.
 * Do not edit by hand.
 *
 * Icons from Lucide (https://lucide.dev), ISC License,
 * Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as part of
 * Feather (MIT). All other copyright (c) for Lucide are held by Lucide Contributors 2022.
 */

/** @type {Readonly<Record<string, readonly string[]>>} */
export const ICONS = Object.freeze({
${body}
});
`);
console.log(`Wrote ${ICON_NAMES.length} icons to ${path.relative(ROOT, OUT_FILE)}`);
